name: rl_tools
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.7

# Add regular dependencies here.
dependencies:
  uuid: ^4.4.0
  yaml: ^3.1.2
  csv: ^6.0.0
  archive: ^3.4.10

dev_dependencies:
  lints: ^3.0.0
  test: ^1.21.0
